import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import ProjectWrap from "./Components/ProjectWrap/ProjectWrap";
import "./globals.css";
import { Suspense } from "react";
import Loading from "./loading";

const prompt = Prompt({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-prompt",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} bg-white`}>
        <Suspense fallback={<Loading />}>
          <ProjectWrap>{children}</ProjectWrap>
        </Suspense>
      </body>
    </html>
  );
}
